### ISSUE TITLE
code wants a config.h but none is generated

### ISSUE THREAD

**Issue by laf0rge** [Manawyrm/ras#1]
```
yate@c3isdn-yate:~/ras$ make
make  all-recursive
make[1]: Entering directory '/home/yate/ras'
Making all in src
make[2]: Entering directory '/home/yate/ras/src'
Making all in .
make[3]: Entering directory '/home/yate/ras/src'
  CC       file_hdlc_decoder.o
file_hdlc_decoder.c:6:10: fatal error: config.h: No such file or directory
    6 | #include "config.h"
      |          ^~~~~~~~~~
```

**Comment by laf0rge** [comment]
ah, it actually is not an autotools-generated "config.h" but it rather seems like the `src/config.h` file was just forgotten to commit?

**Comment by Manawyrm** [comment]
Oops! Yup.
That's an artifact from the .gitignore I copied from another repo, which just ignored config.* outright.

https://github.com/Manawyrm/ras/commit/7c6b2871f27d9fdd5eb0550ece1bf2f0f60b1723 should fix it.

Thanks for reporting :)
